# docker/Dockerfile.dev
FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git curl unzip zip \
    libzip-dev libpng-dev libonig-dev libicu-dev \
    && docker-php-ext-install mysqli pdo pdo_mysql zip intl \
    && pecl install redis && docker-php-ext-enable redis \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY docker/scripts/wait-for-db-dev.sh /usr/local/bin/wait-for-db-dev.sh
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN chmod +x /usr/local/bin/wait-for-db-dev.sh

WORKDIR /var/www

COPY . .

RUN composer install

EXPOSE 8000

ENTRYPOINT ["wait-for-db-dev.sh"]
